import Link from "next/link";
import { ownerSetupAvailable } from "@/lib/admin-owner";
import { BrandLogo } from "@/components/brand/BrandLogo";
import styles from "../login/login.module.css";
export const dynamic="force-dynamic";
export const metadata={title:"Owner setup | BOOM",robots:{index:false,follow:false},referrer:"same-origin"};
export default async function OwnerSetup({searchParams}:{searchParams:Promise<{token?:string;error?:string}>}) {
  const {token="",error}=await searchParams;
  const available=await ownerSetupAvailable(token);
  return <main className={styles.page}><section className={styles.panel}><Link className={styles.brand} href="/"><BrandLogo size={52} priority /></Link><p className={styles.eyebrow}>YOUR BOOM WORKSPACE</p><h1>{available ? "Make it yours." : "Setup link unavailable."}</h1><p className={styles.intro}>{available ? "Choose your email and a private password to manage bookings, payments and prices." : "This private link has expired, has already been used, or is invalid. If you already created your account, sign in below."}</p>
    {available ? <>{error && <p className={styles.error} role="alert">{error === "email" ? "Enter a valid email address for your account." : error === "password" ? "Use at least 8 characters and enter the same password twice." : "Setup could not be completed. Try again or request a fresh link."}</p>}<form method="post" action="/api/admin/setup"><input type="hidden" name="token" value={token} /><label htmlFor="email">Owner email</label><input id="email" name="email" type="email" required maxLength={254} autoComplete="username" /><label htmlFor="password" style={{marginTop:18}}>Choose a password</label><input id="password" type="password" name="password" autoComplete="new-password" minLength={8} maxLength={128} required /><label htmlFor="confirm" style={{marginTop:18}}>Confirm password</label><input id="confirm" type="password" name="confirm" autoComplete="new-password" minLength={8} maxLength={128} required /><button type="submit">Create owner account →</button></form><p className={styles.hint}>Use at least 8 characters. This link works once. Completing setup updates owner access and signs out previous sessions.</p></> : <Link href="/admin/login" className={styles.back}>Sign in to BOOM →</Link>}</section><aside><div><span>Ready for your first customer</span><strong>Your business. Your workspace.</strong><ul className={styles.asideList}><li>See paid bookings and customer details</li><li>Track payment history and website visits</li><li>Keep published service prices up to date</li></ul></div></aside></main>;
}
