import type { BookingConfirmationEmailData } from "./booking-confirmation-template";
export function escapeEmailHtml(value: string) {
  return value.replace(/[&<>'"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[c] ?? c);
}
export function emailAppointment(value: string) {
  const date = new Date(value);
  return { day: new Intl.DateTimeFormat("en-NG", { timeZone: "Africa/Lagos", weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(date), time: new Intl.DateTimeFormat("en-NG", { timeZone: "Africa/Lagos", hour: "numeric", minute: "2-digit", hour12: true }).format(date) };
}
export function emailAmount(total: number, currency: string) { return new Intl.NumberFormat("en-NG", { style: "currency", currency, maximumFractionDigits: 2 }).format(total); }
export function boomEmailLayout(data: BookingConfirmationEmailData, paid: boolean, admin?: { customerEmail: string | null; customerPhone: string | null }) {
  const e = escapeEmailHtml;
  const appointment = emailAppointment(data.scheduledStartAt);
  const amount = emailAmount(data.total, data.currency);
  const name = data.recipientName?.trim() || "there";
  const test = data.mode !== "live";
  const provider = data.paymentProvider || "Paystack";
  const reference = `BOOM-${data.bookingNumber}`;
  const heading = admin ? "A new clean is booked." : paid ? "Your clean is booked." : "One step to your<br>cleaner space.";
  const preview = admin ? `${reference}: payment verified. Appointment details ready for the team.` : paid ? `${reference} is confirmed. Your payment receipt is inside.` : `${reference}: complete payment to confirm your cleaning appointment.`;
  const body = admin ? "Full payment has been verified and this booking is confirmed. Please arrange the cleaning team for the appointment below." : paid ? "Your full payment has been verified and your appointment is confirmed automatically. Here’s everything you need for the day." : "We’ve saved your cleaning details. Complete your full payment through Flutterwave to confirm your appointment automatically.";
  const row = (label: string, value: string) => `<tr><th scope="row" style="padding:15px 0;border-bottom:1px solid #e5eaf1;text-align:left;vertical-align:top;font-size:13px;font-weight:400;color:#64748b;width:31%">${label}</th><td style="padding:15px 0 15px 12px;border-bottom:1px solid #e5eaf1;font-size:15px;line-height:1.6;color:#0f2350;font-weight:600">${value}</td></tr>`;
  const checkout = safeEmailCheckout(data.paymentUrl);
  const cta = paid ? "https://boomcleaning.site" : checkout || "mailto:boomcleaninfo@gmail.com";
  const ctaText = paid ? "Return to home" : checkout ? "Confirm booking with payment" : "Get help with payment";
  return `<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light"><title>${paid ? "Payment receipt and booking confirmation" : "Booking details"} · ${reference}</title><style>@media only screen and (max-width:600px){.outer{padding:16px 8px!important}.pad{padding-left:24px!important;padding-right:24px!important}.headline{font-size:34px!important}.summary{padding:22px!important}.cta{display:block!important;text-align:center!important}}</style></head><body style="margin:0;padding:0;background:#edf2f8;font-family:Arial,Helvetica,sans-serif;color:#0f2350"><div lang="en" dir="ltr"><div style="display:none;font-size:1px;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all">${e(preview)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0"><tr><td class="outer" align="center" style="padding:36px 16px"><table role="presentation" width="600" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:600px;background:white;border-radius:18px;overflow:hidden;border:1px solid #dbe3ee">
<tr><td class="pad" style="padding:30px 40px;background:#0b1a3c;border-bottom:4px solid #55d5f3"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td><a href="https://boomcleaning.site" style="display:inline-block;text-decoration:none"><img src="https://boomcleaning.site/images/boom-logo.png" width="180" height="101" alt="BOOM Cleaning Services" border="0" style="display:block;width:180px;max-width:100%;height:auto;border:0;color:#55d5f3;font-size:18px"></a></td><td align="right" style="color:#c8daf4;font-size:11px;letter-spacing:1px">ABUJA<br><span style="font-size:10px;line-height:2;color:#55d5f3">SPOTLESS STARTS HERE</span></td></tr></table></td></tr>
<tr><td class="pad" style="padding:36px 40px 24px"><p style="margin:0 0 18px;font-size:11px;font-weight:700;letter-spacing:1.5px;color:${paid ? "#16744a" : "#1753c6"}">${paid ? "PAYMENT VERIFIED · BOOKING CONFIRMED" : "BOOKING DETAILS · AWAITING PAYMENT"}</p><h1 class="headline" style="margin:0 0 24px;font-family:Georgia,'Times New Roman',serif;font-size:42px;line-height:1.12;letter-spacing:-1px;font-weight:400;color:#0b1a3c">${heading}</h1><p style="margin:0 0 12px;font-size:16px;line-height:1.7">Hello ${admin ? "BOOM team" : e(name)},</p><p style="margin:0;font-size:16px;line-height:1.7;color:#475569">${body}</p></td></tr>
<tr><td class="pad" style="padding:0 40px 28px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border:1px solid #dbe5f5;background:#f2f6fd;border-radius:12px"><tr><td class="summary" style="padding:26px"><p style="margin:0 0 6px;color:#64748b;font-size:11px;letter-spacing:1.4px">YOUR BOOKING REFERENCE</p><p style="margin:0 0 22px;font-size:24px;letter-spacing:2px;font-weight:700">${reference}</p><p style="margin:0 0 4px;font-size:11px;letter-spacing:1px;color:#64748b">${paid ? "FULL PAYMENT VERIFIED" : "TOTAL DUE TO CONFIRM"}</p><p style="margin:0;color:#1753c6;font-size:34px;font-weight:700;letter-spacing:-1px">${e(amount)}</p>${paid && test ? '<p style="margin:12px 0 0;font-size:12px;line-height:1.6;color:#705421">TEST PAYMENT — No real money was collected.</p>' : paid ? '' : '<p style="margin:12px 0 0;font-size:12px;line-height:1.6;color:#475569">Secure full payment confirms your appointment.</p>'}</td></tr></table></td></tr>
<tr><td class="pad" style="padding:0 40px 26px"><h2 style="margin:0 0 8px;font-size:18px;font-weight:700">Your appointment</h2><table width="100%" cellspacing="0" cellpadding="0" border="0">${admin ? row("Customer", e(name)) + row("Email", e(admin.customerEmail || "Not provided")) + row("Phone", e(admin.customerPhone || "Not provided")) : ""}${row("Service",e(data.serviceName))}${row("Date",e(appointment.day))}${row("Arrival",`${e(appointment.time)} <span style="font-size:12px;font-weight:400;color:#64748b">· Abuja time</span>`)}${row("Address",e(data.address))}${paid ? row("Payment", `${e(provider)}${test ? " · Test mode" : ""} · Paid in full`) : ""}</table></td></tr>
<tr><td class="pad" style="padding:0 40px 34px"><a class="cta" href="${e(cta)}" style="display:inline-block;padding:16px 24px;background:#1753c6;border-radius:8px;font-size:14px;line-height:1.3;font-weight:700;color:white;text-decoration:none">${ctaText} &nbsp;→</a>${admin ? "" : `<p style="margin:20px 0 0;font-size:13px;line-height:1.8;color:#64748b">${paid ? "Please make sure our team can access the property at your selected arrival time. For a change to your appointment, reply with your booking reference." : "Keep this reference handy. Once payment is verified, we’ll email your receipt and booking confirmation."}</p>`}</td></tr>
<tr><td class="pad" style="padding:24px 40px;background:#f7f9fc;border-top:1px solid #e5eaf1"><p style="margin:0 0 10px;font-size:13px;color:#475569">A spotless space. A little more peace of mind.</p><p style="margin:0;font-size:12px;line-height:1.8;color:#64748b"><a href="mailto:boomcleaninfo@gmail.com" style="color:#1753c6;text-decoration:none">Email BOOM</a> &nbsp;·&nbsp; <a href="tel:+2349029799205" style="color:#1753c6;text-decoration:none">Call the team</a> &nbsp;·&nbsp; <a href="https://www.instagram.com/boom_cleaning_services/" style="color:#1753c6;text-decoration:none">Instagram</a></p></td></tr></table><p style="margin:18px 0 0;font-size:11px;line-height:1.6;color:#64748b">BOOM Cleaning Services · Abuja, Nigeria<br>You’re receiving this email about booking ${reference}.</p></td></tr></table></div></body></html>`;
}

function safeEmailCheckout(value?: string | null) {
 if (!value) return null;
 try { const url = new URL(value); return url.protocol === "https:" && !url.username && !url.password && ((url.hostname === "checkout.flutterwave.com" && url.pathname.startsWith("/v3/hosted/pay/")) || (url.hostname === "checkout.paystack.com" && /^\/[A-Za-z0-9]+$/.test(url.pathname))) ? value : null; } catch { return null; }
}
